// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package com.liukai.proto;

public final class MetaModel {
  private MetaModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BrandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:look.meta.Brand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 修改表的initial value=10000
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     * 英文名
     * </pre>
     *
     * <code>optional string name_en = 2;</code>
     */
    java.lang.String getNameEn();
    /**
     * <pre>
     * 英文名
     * </pre>
     *
     * <code>optional string name_en = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameEnBytes();

    /**
     * <pre>
     * 中文名
     * </pre>
     *
     * <code>optional string name_zh = 3;</code>
     */
    java.lang.String getNameZh();
    /**
     * <pre>
     * 中文名
     * </pre>
     *
     * <code>optional string name_zh = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameZhBytes();

    /**
     * <code>optional string pinyin = 4;</code>
     */
    java.lang.String getPinyin();
    /**
     * <code>optional string pinyin = 4;</code>
     */
    com.google.protobuf.ByteString
        getPinyinBytes();

    /**
     * <pre>
     * 搜索词
     * </pre>
     *
     * <code>repeated string search_word = 5;</code>
     */
    java.util.List<java.lang.String>
        getSearchWordList();
    /**
     * <pre>
     * 搜索词
     * </pre>
     *
     * <code>repeated string search_word = 5;</code>
     */
    int getSearchWordCount();
    /**
     * <pre>
     * 搜索词
     * </pre>
     *
     * <code>repeated string search_word = 5;</code>
     */
    java.lang.String getSearchWord(int index);
    /**
     * <pre>
     * 搜索词
     * </pre>
     *
     * <code>repeated string search_word = 5;</code>
     */
    com.google.protobuf.ByteString
        getSearchWordBytes(int index);

    /**
     * <pre>
     * 国家code
     * </pre>
     *
     * <code>optional string country = 6;</code>
     */
    java.lang.String getCountry();
    /**
     * <pre>
     * 国家code
     * </pre>
     *
     * <code>optional string country = 6;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <pre>
     * 介绍
     * </pre>
     *
     * <code>optional string description = 7;</code>
     */
    java.lang.String getDescription();
    /**
     * <pre>
     * 介绍
     * </pre>
     *
     * <code>optional string description = 7;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <pre>
     * logo的resource path
     * </pre>
     *
     * <code>optional string logo_path = 8;</code>
     */
    java.lang.String getLogoPath();
    /**
     * <pre>
     * logo的resource path
     * </pre>
     *
     * <code>optional string logo_path = 8;</code>
     */
    com.google.protobuf.ByteString
        getLogoPathBytes();

    /**
     * <pre>
     * logo的image url
     * </pre>
     *
     * <code>optional string logo_url = 9;</code>
     */
    java.lang.String getLogoUrl();
    /**
     * <pre>
     * logo的image url
     * </pre>
     *
     * <code>optional string logo_url = 9;</code>
     */
    com.google.protobuf.ByteString
        getLogoUrlBytes();

    /**
     * <pre>
     * cover的resource path
     * </pre>
     *
     * <code>optional string cover_path = 10;</code>
     */
    java.lang.String getCoverPath();
    /**
     * <pre>
     * cover的resource path
     * </pre>
     *
     * <code>optional string cover_path = 10;</code>
     */
    com.google.protobuf.ByteString
        getCoverPathBytes();

    /**
     * <pre>
     * cover的image url
     * </pre>
     *
     * <code>optional string cover_url = 11;</code>
     */
    java.lang.String getCoverUrl();
    /**
     * <pre>
     * cover的image url
     * </pre>
     *
     * <code>optional string cover_url = 11;</code>
     */
    com.google.protobuf.ByteString
        getCoverUrlBytes();

    /**
     * <code>optional bool if_del = 40;</code>
     */
    boolean getIfDel();

    /**
     * <code>optional bool if_publish = 41;</code>
     */
    boolean getIfPublish();

    /**
     * <code>map&lt;string, string&gt; payload = 42;</code>
     */
    int getPayloadCount();
    /**
     * <code>map&lt;string, string&gt; payload = 42;</code>
     */
    boolean containsPayload(
        java.lang.String key);
    /**
     * Use {@link #getPayloadMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getPayload();
    /**
     * <code>map&lt;string, string&gt; payload = 42;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getPayloadMap();
    /**
     * <code>map&lt;string, string&gt; payload = 42;</code>
     */

    java.lang.String getPayloadOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; payload = 42;</code>
     */

    java.lang.String getPayloadOrThrow(
        java.lang.String key);

    /**
     * <code>optional int64 last_modify_user = 43;</code>
     */
    long getLastModifyUser();

    /**
     * <code>optional int64 create_time = 50;</code>
     */
    long getCreateTime();

    /**
     * <code>optional int64 update_time = 51;</code>
     */
    long getUpdateTime();

    /**
     * <code>optional int64 delete_time = 52;</code>
     */
    long getDeleteTime();
  }
  /**
   * Protobuf type {@code look.meta.Brand}
   */
  public  static final class Brand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:look.meta.Brand)
      BrandOrBuilder {
    // Use Brand.newBuilder() to construct.
    private Brand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Brand() {
      id_ = 0L;
      nameEn_ = "";
      nameZh_ = "";
      pinyin_ = "";
      searchWord_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      country_ = "";
      description_ = "";
      logoPath_ = "";
      logoUrl_ = "";
      coverPath_ = "";
      coverUrl_ = "";
      ifDel_ = false;
      ifPublish_ = false;
      lastModifyUser_ = 0L;
      createTime_ = 0L;
      updateTime_ = 0L;
      deleteTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Brand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nameEn_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              nameZh_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              pinyin_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                searchWord_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              searchWord_.add(s);
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              country_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              logoPath_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              logoUrl_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              coverPath_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              coverUrl_ = s;
              break;
            }
            case 320: {

              ifDel_ = input.readBool();
              break;
            }
            case 328: {

              ifPublish_ = input.readBool();
              break;
            }
            case 338: {
              if (!((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
                payload_ = com.google.protobuf.MapField.newMapField(
                    PayloadDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00002000;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              payload = input.readMessage(
                  PayloadDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              payload_.getMutableMap().put(payload.getKey(), payload.getValue());
              break;
            }
            case 344: {

              lastModifyUser_ = input.readInt64();
              break;
            }
            case 400: {

              createTime_ = input.readInt64();
              break;
            }
            case 408: {

              updateTime_ = input.readInt64();
              break;
            }
            case 416: {

              deleteTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          searchWord_ = searchWord_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.liukai.proto.MetaModel.internal_static_look_meta_Brand_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 42:
          return internalGetPayload();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.liukai.proto.MetaModel.internal_static_look_meta_Brand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.liukai.proto.MetaModel.Brand.class, com.liukai.proto.MetaModel.Brand.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * 修改表的initial value=10000
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_EN_FIELD_NUMBER = 2;
    private volatile java.lang.Object nameEn_;
    /**
     * <pre>
     * 英文名
     * </pre>
     *
     * <code>optional string name_en = 2;</code>
     */
    public java.lang.String getNameEn() {
      java.lang.Object ref = nameEn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameEn_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 英文名
     * </pre>
     *
     * <code>optional string name_en = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameEnBytes() {
      java.lang.Object ref = nameEn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameEn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_ZH_FIELD_NUMBER = 3;
    private volatile java.lang.Object nameZh_;
    /**
     * <pre>
     * 中文名
     * </pre>
     *
     * <code>optional string name_zh = 3;</code>
     */
    public java.lang.String getNameZh() {
      java.lang.Object ref = nameZh_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameZh_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 中文名
     * </pre>
     *
     * <code>optional string name_zh = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameZhBytes() {
      java.lang.Object ref = nameZh_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameZh_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PINYIN_FIELD_NUMBER = 4;
    private volatile java.lang.Object pinyin_;
    /**
     * <code>optional string pinyin = 4;</code>
     */
    public java.lang.String getPinyin() {
      java.lang.Object ref = pinyin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pinyin_ = s;
        return s;
      }
    }
    /**
     * <code>optional string pinyin = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPinyinBytes() {
      java.lang.Object ref = pinyin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pinyin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEARCH_WORD_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList searchWord_;
    /**
     * <pre>
     * 搜索词
     * </pre>
     *
     * <code>repeated string search_word = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSearchWordList() {
      return searchWord_;
    }
    /**
     * <pre>
     * 搜索词
     * </pre>
     *
     * <code>repeated string search_word = 5;</code>
     */
    public int getSearchWordCount() {
      return searchWord_.size();
    }
    /**
     * <pre>
     * 搜索词
     * </pre>
     *
     * <code>repeated string search_word = 5;</code>
     */
    public java.lang.String getSearchWord(int index) {
      return searchWord_.get(index);
    }
    /**
     * <pre>
     * 搜索词
     * </pre>
     *
     * <code>repeated string search_word = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSearchWordBytes(int index) {
      return searchWord_.getByteString(index);
    }

    public static final int COUNTRY_FIELD_NUMBER = 6;
    private volatile java.lang.Object country_;
    /**
     * <pre>
     * 国家code
     * </pre>
     *
     * <code>optional string country = 6;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 国家code
     * </pre>
     *
     * <code>optional string country = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 7;
    private volatile java.lang.Object description_;
    /**
     * <pre>
     * 介绍
     * </pre>
     *
     * <code>optional string description = 7;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 介绍
     * </pre>
     *
     * <code>optional string description = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGO_PATH_FIELD_NUMBER = 8;
    private volatile java.lang.Object logoPath_;
    /**
     * <pre>
     * logo的resource path
     * </pre>
     *
     * <code>optional string logo_path = 8;</code>
     */
    public java.lang.String getLogoPath() {
      java.lang.Object ref = logoPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logoPath_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * logo的resource path
     * </pre>
     *
     * <code>optional string logo_path = 8;</code>
     */
    public com.google.protobuf.ByteString
        getLogoPathBytes() {
      java.lang.Object ref = logoPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logoPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGO_URL_FIELD_NUMBER = 9;
    private volatile java.lang.Object logoUrl_;
    /**
     * <pre>
     * logo的image url
     * </pre>
     *
     * <code>optional string logo_url = 9;</code>
     */
    public java.lang.String getLogoUrl() {
      java.lang.Object ref = logoUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logoUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * logo的image url
     * </pre>
     *
     * <code>optional string logo_url = 9;</code>
     */
    public com.google.protobuf.ByteString
        getLogoUrlBytes() {
      java.lang.Object ref = logoUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logoUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COVER_PATH_FIELD_NUMBER = 10;
    private volatile java.lang.Object coverPath_;
    /**
     * <pre>
     * cover的resource path
     * </pre>
     *
     * <code>optional string cover_path = 10;</code>
     */
    public java.lang.String getCoverPath() {
      java.lang.Object ref = coverPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        coverPath_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * cover的resource path
     * </pre>
     *
     * <code>optional string cover_path = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCoverPathBytes() {
      java.lang.Object ref = coverPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        coverPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COVER_URL_FIELD_NUMBER = 11;
    private volatile java.lang.Object coverUrl_;
    /**
     * <pre>
     * cover的image url
     * </pre>
     *
     * <code>optional string cover_url = 11;</code>
     */
    public java.lang.String getCoverUrl() {
      java.lang.Object ref = coverUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        coverUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * cover的image url
     * </pre>
     *
     * <code>optional string cover_url = 11;</code>
     */
    public com.google.protobuf.ByteString
        getCoverUrlBytes() {
      java.lang.Object ref = coverUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        coverUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IF_DEL_FIELD_NUMBER = 40;
    private boolean ifDel_;
    /**
     * <code>optional bool if_del = 40;</code>
     */
    public boolean getIfDel() {
      return ifDel_;
    }

    public static final int IF_PUBLISH_FIELD_NUMBER = 41;
    private boolean ifPublish_;
    /**
     * <code>optional bool if_publish = 41;</code>
     */
    public boolean getIfPublish() {
      return ifPublish_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 42;
    private static final class PayloadDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.liukai.proto.MetaModel.internal_static_look_meta_Brand_PayloadEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> payload_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetPayload() {
      if (payload_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PayloadDefaultEntryHolder.defaultEntry);
      }
      return payload_;
    }

    public int getPayloadCount() {
      return internalGetPayload().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; payload = 42;</code>
     */

    public boolean containsPayload(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetPayload().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPayloadMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getPayload() {
      return getPayloadMap();
    }
    /**
     * <code>map&lt;string, string&gt; payload = 42;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getPayloadMap() {
      return internalGetPayload().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; payload = 42;</code>
     */

    public java.lang.String getPayloadOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetPayload().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; payload = 42;</code>
     */

    public java.lang.String getPayloadOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetPayload().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int LAST_MODIFY_USER_FIELD_NUMBER = 43;
    private long lastModifyUser_;
    /**
     * <code>optional int64 last_modify_user = 43;</code>
     */
    public long getLastModifyUser() {
      return lastModifyUser_;
    }

    public static final int CREATE_TIME_FIELD_NUMBER = 50;
    private long createTime_;
    /**
     * <code>optional int64 create_time = 50;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int UPDATE_TIME_FIELD_NUMBER = 51;
    private long updateTime_;
    /**
     * <code>optional int64 update_time = 51;</code>
     */
    public long getUpdateTime() {
      return updateTime_;
    }

    public static final int DELETE_TIME_FIELD_NUMBER = 52;
    private long deleteTime_;
    /**
     * <code>optional int64 delete_time = 52;</code>
     */
    public long getDeleteTime() {
      return deleteTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameEnBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nameEn_);
      }
      if (!getNameZhBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nameZh_);
      }
      if (!getPinyinBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, pinyin_);
      }
      for (int i = 0; i < searchWord_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, searchWord_.getRaw(i));
      }
      if (!getCountryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, country_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, description_);
      }
      if (!getLogoPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, logoPath_);
      }
      if (!getLogoUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, logoUrl_);
      }
      if (!getCoverPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, coverPath_);
      }
      if (!getCoverUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, coverUrl_);
      }
      if (ifDel_ != false) {
        output.writeBool(40, ifDel_);
      }
      if (ifPublish_ != false) {
        output.writeBool(41, ifPublish_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetPayload().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        payload = PayloadDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(42, payload);
      }
      if (lastModifyUser_ != 0L) {
        output.writeInt64(43, lastModifyUser_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(50, createTime_);
      }
      if (updateTime_ != 0L) {
        output.writeInt64(51, updateTime_);
      }
      if (deleteTime_ != 0L) {
        output.writeInt64(52, deleteTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameEnBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nameEn_);
      }
      if (!getNameZhBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nameZh_);
      }
      if (!getPinyinBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, pinyin_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < searchWord_.size(); i++) {
          dataSize += computeStringSizeNoTag(searchWord_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSearchWordList().size();
      }
      if (!getCountryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, country_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, description_);
      }
      if (!getLogoPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, logoPath_);
      }
      if (!getLogoUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, logoUrl_);
      }
      if (!getCoverPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, coverPath_);
      }
      if (!getCoverUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, coverUrl_);
      }
      if (ifDel_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(40, ifDel_);
      }
      if (ifPublish_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(41, ifPublish_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetPayload().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        payload = PayloadDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(42, payload);
      }
      if (lastModifyUser_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(43, lastModifyUser_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(50, createTime_);
      }
      if (updateTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(51, updateTime_);
      }
      if (deleteTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(52, deleteTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.liukai.proto.MetaModel.Brand)) {
        return super.equals(obj);
      }
      com.liukai.proto.MetaModel.Brand other = (com.liukai.proto.MetaModel.Brand) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getNameEn()
          .equals(other.getNameEn());
      result = result && getNameZh()
          .equals(other.getNameZh());
      result = result && getPinyin()
          .equals(other.getPinyin());
      result = result && getSearchWordList()
          .equals(other.getSearchWordList());
      result = result && getCountry()
          .equals(other.getCountry());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && getLogoPath()
          .equals(other.getLogoPath());
      result = result && getLogoUrl()
          .equals(other.getLogoUrl());
      result = result && getCoverPath()
          .equals(other.getCoverPath());
      result = result && getCoverUrl()
          .equals(other.getCoverUrl());
      result = result && (getIfDel()
          == other.getIfDel());
      result = result && (getIfPublish()
          == other.getIfPublish());
      result = result && internalGetPayload().equals(
          other.internalGetPayload());
      result = result && (getLastModifyUser()
          == other.getLastModifyUser());
      result = result && (getCreateTime()
          == other.getCreateTime());
      result = result && (getUpdateTime()
          == other.getUpdateTime());
      result = result && (getDeleteTime()
          == other.getDeleteTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_EN_FIELD_NUMBER;
      hash = (53 * hash) + getNameEn().hashCode();
      hash = (37 * hash) + NAME_ZH_FIELD_NUMBER;
      hash = (53 * hash) + getNameZh().hashCode();
      hash = (37 * hash) + PINYIN_FIELD_NUMBER;
      hash = (53 * hash) + getPinyin().hashCode();
      if (getSearchWordCount() > 0) {
        hash = (37 * hash) + SEARCH_WORD_FIELD_NUMBER;
        hash = (53 * hash) + getSearchWordList().hashCode();
      }
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + LOGO_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getLogoPath().hashCode();
      hash = (37 * hash) + LOGO_URL_FIELD_NUMBER;
      hash = (53 * hash) + getLogoUrl().hashCode();
      hash = (37 * hash) + COVER_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getCoverPath().hashCode();
      hash = (37 * hash) + COVER_URL_FIELD_NUMBER;
      hash = (53 * hash) + getCoverUrl().hashCode();
      hash = (37 * hash) + IF_DEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIfDel());
      hash = (37 * hash) + IF_PUBLISH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIfPublish());
      if (!internalGetPayload().getMap().isEmpty()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + internalGetPayload().hashCode();
      }
      hash = (37 * hash) + LAST_MODIFY_USER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastModifyUser());
      hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + UPDATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdateTime());
      hash = (37 * hash) + DELETE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDeleteTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.liukai.proto.MetaModel.Brand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liukai.proto.MetaModel.Brand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liukai.proto.MetaModel.Brand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liukai.proto.MetaModel.Brand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liukai.proto.MetaModel.Brand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.liukai.proto.MetaModel.Brand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.liukai.proto.MetaModel.Brand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.liukai.proto.MetaModel.Brand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.liukai.proto.MetaModel.Brand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.liukai.proto.MetaModel.Brand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.liukai.proto.MetaModel.Brand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code look.meta.Brand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:look.meta.Brand)
        com.liukai.proto.MetaModel.BrandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.liukai.proto.MetaModel.internal_static_look_meta_Brand_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 42:
            return internalGetPayload();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 42:
            return internalGetMutablePayload();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.liukai.proto.MetaModel.internal_static_look_meta_Brand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.liukai.proto.MetaModel.Brand.class, com.liukai.proto.MetaModel.Brand.Builder.class);
      }

      // Construct using com.liukai.proto.MetaModel.Brand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        nameEn_ = "";

        nameZh_ = "";

        pinyin_ = "";

        searchWord_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        country_ = "";

        description_ = "";

        logoPath_ = "";

        logoUrl_ = "";

        coverPath_ = "";

        coverUrl_ = "";

        ifDel_ = false;

        ifPublish_ = false;

        internalGetMutablePayload().clear();
        lastModifyUser_ = 0L;

        createTime_ = 0L;

        updateTime_ = 0L;

        deleteTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.liukai.proto.MetaModel.internal_static_look_meta_Brand_descriptor;
      }

      public com.liukai.proto.MetaModel.Brand getDefaultInstanceForType() {
        return com.liukai.proto.MetaModel.Brand.getDefaultInstance();
      }

      public com.liukai.proto.MetaModel.Brand build() {
        com.liukai.proto.MetaModel.Brand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.liukai.proto.MetaModel.Brand buildPartial() {
        com.liukai.proto.MetaModel.Brand result = new com.liukai.proto.MetaModel.Brand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.nameEn_ = nameEn_;
        result.nameZh_ = nameZh_;
        result.pinyin_ = pinyin_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          searchWord_ = searchWord_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.searchWord_ = searchWord_;
        result.country_ = country_;
        result.description_ = description_;
        result.logoPath_ = logoPath_;
        result.logoUrl_ = logoUrl_;
        result.coverPath_ = coverPath_;
        result.coverUrl_ = coverUrl_;
        result.ifDel_ = ifDel_;
        result.ifPublish_ = ifPublish_;
        result.payload_ = internalGetPayload();
        result.payload_.makeImmutable();
        result.lastModifyUser_ = lastModifyUser_;
        result.createTime_ = createTime_;
        result.updateTime_ = updateTime_;
        result.deleteTime_ = deleteTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.liukai.proto.MetaModel.Brand) {
          return mergeFrom((com.liukai.proto.MetaModel.Brand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.liukai.proto.MetaModel.Brand other) {
        if (other == com.liukai.proto.MetaModel.Brand.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getNameEn().isEmpty()) {
          nameEn_ = other.nameEn_;
          onChanged();
        }
        if (!other.getNameZh().isEmpty()) {
          nameZh_ = other.nameZh_;
          onChanged();
        }
        if (!other.getPinyin().isEmpty()) {
          pinyin_ = other.pinyin_;
          onChanged();
        }
        if (!other.searchWord_.isEmpty()) {
          if (searchWord_.isEmpty()) {
            searchWord_ = other.searchWord_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSearchWordIsMutable();
            searchWord_.addAll(other.searchWord_);
          }
          onChanged();
        }
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getLogoPath().isEmpty()) {
          logoPath_ = other.logoPath_;
          onChanged();
        }
        if (!other.getLogoUrl().isEmpty()) {
          logoUrl_ = other.logoUrl_;
          onChanged();
        }
        if (!other.getCoverPath().isEmpty()) {
          coverPath_ = other.coverPath_;
          onChanged();
        }
        if (!other.getCoverUrl().isEmpty()) {
          coverUrl_ = other.coverUrl_;
          onChanged();
        }
        if (other.getIfDel() != false) {
          setIfDel(other.getIfDel());
        }
        if (other.getIfPublish() != false) {
          setIfPublish(other.getIfPublish());
        }
        internalGetMutablePayload().mergeFrom(
            other.internalGetPayload());
        if (other.getLastModifyUser() != 0L) {
          setLastModifyUser(other.getLastModifyUser());
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.getUpdateTime() != 0L) {
          setUpdateTime(other.getUpdateTime());
        }
        if (other.getDeleteTime() != 0L) {
          setDeleteTime(other.getDeleteTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.liukai.proto.MetaModel.Brand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.liukai.proto.MetaModel.Brand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <pre>
       * 修改表的initial value=10000
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * 修改表的initial value=10000
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 修改表的initial value=10000
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object nameEn_ = "";
      /**
       * <pre>
       * 英文名
       * </pre>
       *
       * <code>optional string name_en = 2;</code>
       */
      public java.lang.String getNameEn() {
        java.lang.Object ref = nameEn_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nameEn_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 英文名
       * </pre>
       *
       * <code>optional string name_en = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameEnBytes() {
        java.lang.Object ref = nameEn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nameEn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 英文名
       * </pre>
       *
       * <code>optional string name_en = 2;</code>
       */
      public Builder setNameEn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nameEn_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 英文名
       * </pre>
       *
       * <code>optional string name_en = 2;</code>
       */
      public Builder clearNameEn() {
        
        nameEn_ = getDefaultInstance().getNameEn();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 英文名
       * </pre>
       *
       * <code>optional string name_en = 2;</code>
       */
      public Builder setNameEnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nameEn_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nameZh_ = "";
      /**
       * <pre>
       * 中文名
       * </pre>
       *
       * <code>optional string name_zh = 3;</code>
       */
      public java.lang.String getNameZh() {
        java.lang.Object ref = nameZh_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nameZh_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 中文名
       * </pre>
       *
       * <code>optional string name_zh = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameZhBytes() {
        java.lang.Object ref = nameZh_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nameZh_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 中文名
       * </pre>
       *
       * <code>optional string name_zh = 3;</code>
       */
      public Builder setNameZh(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nameZh_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 中文名
       * </pre>
       *
       * <code>optional string name_zh = 3;</code>
       */
      public Builder clearNameZh() {
        
        nameZh_ = getDefaultInstance().getNameZh();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 中文名
       * </pre>
       *
       * <code>optional string name_zh = 3;</code>
       */
      public Builder setNameZhBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nameZh_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pinyin_ = "";
      /**
       * <code>optional string pinyin = 4;</code>
       */
      public java.lang.String getPinyin() {
        java.lang.Object ref = pinyin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pinyin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pinyin = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPinyinBytes() {
        java.lang.Object ref = pinyin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pinyin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pinyin = 4;</code>
       */
      public Builder setPinyin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pinyin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pinyin = 4;</code>
       */
      public Builder clearPinyin() {
        
        pinyin_ = getDefaultInstance().getPinyin();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pinyin = 4;</code>
       */
      public Builder setPinyinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pinyin_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList searchWord_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSearchWordIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          searchWord_ = new com.google.protobuf.LazyStringArrayList(searchWord_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <pre>
       * 搜索词
       * </pre>
       *
       * <code>repeated string search_word = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSearchWordList() {
        return searchWord_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 搜索词
       * </pre>
       *
       * <code>repeated string search_word = 5;</code>
       */
      public int getSearchWordCount() {
        return searchWord_.size();
      }
      /**
       * <pre>
       * 搜索词
       * </pre>
       *
       * <code>repeated string search_word = 5;</code>
       */
      public java.lang.String getSearchWord(int index) {
        return searchWord_.get(index);
      }
      /**
       * <pre>
       * 搜索词
       * </pre>
       *
       * <code>repeated string search_word = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSearchWordBytes(int index) {
        return searchWord_.getByteString(index);
      }
      /**
       * <pre>
       * 搜索词
       * </pre>
       *
       * <code>repeated string search_word = 5;</code>
       */
      public Builder setSearchWord(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSearchWordIsMutable();
        searchWord_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 搜索词
       * </pre>
       *
       * <code>repeated string search_word = 5;</code>
       */
      public Builder addSearchWord(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSearchWordIsMutable();
        searchWord_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 搜索词
       * </pre>
       *
       * <code>repeated string search_word = 5;</code>
       */
      public Builder addAllSearchWord(
          java.lang.Iterable<java.lang.String> values) {
        ensureSearchWordIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, searchWord_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 搜索词
       * </pre>
       *
       * <code>repeated string search_word = 5;</code>
       */
      public Builder clearSearchWord() {
        searchWord_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 搜索词
       * </pre>
       *
       * <code>repeated string search_word = 5;</code>
       */
      public Builder addSearchWordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSearchWordIsMutable();
        searchWord_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <pre>
       * 国家code
       * </pre>
       *
       * <code>optional string country = 6;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 国家code
       * </pre>
       *
       * <code>optional string country = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 国家code
       * </pre>
       *
       * <code>optional string country = 6;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 国家code
       * </pre>
       *
       * <code>optional string country = 6;</code>
       */
      public Builder clearCountry() {
        
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 国家code
       * </pre>
       *
       * <code>optional string country = 6;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        country_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <pre>
       * 介绍
       * </pre>
       *
       * <code>optional string description = 7;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 介绍
       * </pre>
       *
       * <code>optional string description = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 介绍
       * </pre>
       *
       * <code>optional string description = 7;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 介绍
       * </pre>
       *
       * <code>optional string description = 7;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 介绍
       * </pre>
       *
       * <code>optional string description = 7;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object logoPath_ = "";
      /**
       * <pre>
       * logo的resource path
       * </pre>
       *
       * <code>optional string logo_path = 8;</code>
       */
      public java.lang.String getLogoPath() {
        java.lang.Object ref = logoPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logoPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * logo的resource path
       * </pre>
       *
       * <code>optional string logo_path = 8;</code>
       */
      public com.google.protobuf.ByteString
          getLogoPathBytes() {
        java.lang.Object ref = logoPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logoPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * logo的resource path
       * </pre>
       *
       * <code>optional string logo_path = 8;</code>
       */
      public Builder setLogoPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logoPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * logo的resource path
       * </pre>
       *
       * <code>optional string logo_path = 8;</code>
       */
      public Builder clearLogoPath() {
        
        logoPath_ = getDefaultInstance().getLogoPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * logo的resource path
       * </pre>
       *
       * <code>optional string logo_path = 8;</code>
       */
      public Builder setLogoPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logoPath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object logoUrl_ = "";
      /**
       * <pre>
       * logo的image url
       * </pre>
       *
       * <code>optional string logo_url = 9;</code>
       */
      public java.lang.String getLogoUrl() {
        java.lang.Object ref = logoUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logoUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * logo的image url
       * </pre>
       *
       * <code>optional string logo_url = 9;</code>
       */
      public com.google.protobuf.ByteString
          getLogoUrlBytes() {
        java.lang.Object ref = logoUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logoUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * logo的image url
       * </pre>
       *
       * <code>optional string logo_url = 9;</code>
       */
      public Builder setLogoUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logoUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * logo的image url
       * </pre>
       *
       * <code>optional string logo_url = 9;</code>
       */
      public Builder clearLogoUrl() {
        
        logoUrl_ = getDefaultInstance().getLogoUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * logo的image url
       * </pre>
       *
       * <code>optional string logo_url = 9;</code>
       */
      public Builder setLogoUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logoUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object coverPath_ = "";
      /**
       * <pre>
       * cover的resource path
       * </pre>
       *
       * <code>optional string cover_path = 10;</code>
       */
      public java.lang.String getCoverPath() {
        java.lang.Object ref = coverPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          coverPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * cover的resource path
       * </pre>
       *
       * <code>optional string cover_path = 10;</code>
       */
      public com.google.protobuf.ByteString
          getCoverPathBytes() {
        java.lang.Object ref = coverPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          coverPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * cover的resource path
       * </pre>
       *
       * <code>optional string cover_path = 10;</code>
       */
      public Builder setCoverPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        coverPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * cover的resource path
       * </pre>
       *
       * <code>optional string cover_path = 10;</code>
       */
      public Builder clearCoverPath() {
        
        coverPath_ = getDefaultInstance().getCoverPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * cover的resource path
       * </pre>
       *
       * <code>optional string cover_path = 10;</code>
       */
      public Builder setCoverPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        coverPath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object coverUrl_ = "";
      /**
       * <pre>
       * cover的image url
       * </pre>
       *
       * <code>optional string cover_url = 11;</code>
       */
      public java.lang.String getCoverUrl() {
        java.lang.Object ref = coverUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          coverUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * cover的image url
       * </pre>
       *
       * <code>optional string cover_url = 11;</code>
       */
      public com.google.protobuf.ByteString
          getCoverUrlBytes() {
        java.lang.Object ref = coverUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          coverUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * cover的image url
       * </pre>
       *
       * <code>optional string cover_url = 11;</code>
       */
      public Builder setCoverUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        coverUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * cover的image url
       * </pre>
       *
       * <code>optional string cover_url = 11;</code>
       */
      public Builder clearCoverUrl() {
        
        coverUrl_ = getDefaultInstance().getCoverUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * cover的image url
       * </pre>
       *
       * <code>optional string cover_url = 11;</code>
       */
      public Builder setCoverUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        coverUrl_ = value;
        onChanged();
        return this;
      }

      private boolean ifDel_ ;
      /**
       * <code>optional bool if_del = 40;</code>
       */
      public boolean getIfDel() {
        return ifDel_;
      }
      /**
       * <code>optional bool if_del = 40;</code>
       */
      public Builder setIfDel(boolean value) {
        
        ifDel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool if_del = 40;</code>
       */
      public Builder clearIfDel() {
        
        ifDel_ = false;
        onChanged();
        return this;
      }

      private boolean ifPublish_ ;
      /**
       * <code>optional bool if_publish = 41;</code>
       */
      public boolean getIfPublish() {
        return ifPublish_;
      }
      /**
       * <code>optional bool if_publish = 41;</code>
       */
      public Builder setIfPublish(boolean value) {
        
        ifPublish_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool if_publish = 41;</code>
       */
      public Builder clearIfPublish() {
        
        ifPublish_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> payload_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetPayload() {
        if (payload_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PayloadDefaultEntryHolder.defaultEntry);
        }
        return payload_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutablePayload() {
        onChanged();;
        if (payload_ == null) {
          payload_ = com.google.protobuf.MapField.newMapField(
              PayloadDefaultEntryHolder.defaultEntry);
        }
        if (!payload_.isMutable()) {
          payload_ = payload_.copy();
        }
        return payload_;
      }

      public int getPayloadCount() {
        return internalGetPayload().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; payload = 42;</code>
       */

      public boolean containsPayload(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetPayload().getMap().containsKey(key);
      }
      /**
       * Use {@link #getPayloadMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getPayload() {
        return getPayloadMap();
      }
      /**
       * <code>map&lt;string, string&gt; payload = 42;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getPayloadMap() {
        return internalGetPayload().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; payload = 42;</code>
       */

      public java.lang.String getPayloadOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetPayload().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; payload = 42;</code>
       */

      public java.lang.String getPayloadOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetPayload().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearPayload() {
        getMutablePayload().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; payload = 42;</code>
       */

      public Builder removePayload(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutablePayload().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutablePayload() {
        return internalGetMutablePayload().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; payload = 42;</code>
       */
      public Builder putPayload(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutablePayload().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; payload = 42;</code>
       */

      public Builder putAllPayload(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutablePayload().putAll(values);
        return this;
      }

      private long lastModifyUser_ ;
      /**
       * <code>optional int64 last_modify_user = 43;</code>
       */
      public long getLastModifyUser() {
        return lastModifyUser_;
      }
      /**
       * <code>optional int64 last_modify_user = 43;</code>
       */
      public Builder setLastModifyUser(long value) {
        
        lastModifyUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 last_modify_user = 43;</code>
       */
      public Builder clearLastModifyUser() {
        
        lastModifyUser_ = 0L;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>optional int64 create_time = 50;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional int64 create_time = 50;</code>
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 create_time = 50;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private long updateTime_ ;
      /**
       * <code>optional int64 update_time = 51;</code>
       */
      public long getUpdateTime() {
        return updateTime_;
      }
      /**
       * <code>optional int64 update_time = 51;</code>
       */
      public Builder setUpdateTime(long value) {
        
        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 update_time = 51;</code>
       */
      public Builder clearUpdateTime() {
        
        updateTime_ = 0L;
        onChanged();
        return this;
      }

      private long deleteTime_ ;
      /**
       * <code>optional int64 delete_time = 52;</code>
       */
      public long getDeleteTime() {
        return deleteTime_;
      }
      /**
       * <code>optional int64 delete_time = 52;</code>
       */
      public Builder setDeleteTime(long value) {
        
        deleteTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 delete_time = 52;</code>
       */
      public Builder clearDeleteTime() {
        
        deleteTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:look.meta.Brand)
    }

    // @@protoc_insertion_point(class_scope:look.meta.Brand)
    private static final com.liukai.proto.MetaModel.Brand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.liukai.proto.MetaModel.Brand();
    }

    public static com.liukai.proto.MetaModel.Brand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Brand>
        PARSER = new com.google.protobuf.AbstractParser<Brand>() {
      public Brand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Brand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Brand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Brand> getParserForType() {
      return PARSER;
    }

    public com.liukai.proto.MetaModel.Brand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_look_meta_Brand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_look_meta_Brand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_look_meta_Brand_PayloadEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_look_meta_Brand_PayloadEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmeta.proto\022\tlook.meta\"\251\003\n\005Brand\022\n\n\002id\030" +
      "\001 \001(\003\022\017\n\007name_en\030\002 \001(\t\022\017\n\007name_zh\030\003 \001(\t\022" +
      "\016\n\006pinyin\030\004 \001(\t\022\023\n\013search_word\030\005 \003(\t\022\017\n\007" +
      "country\030\006 \001(\t\022\023\n\013description\030\007 \001(\t\022\021\n\tlo" +
      "go_path\030\010 \001(\t\022\020\n\010logo_url\030\t \001(\t\022\022\n\ncover" +
      "_path\030\n \001(\t\022\021\n\tcover_url\030\013 \001(\t\022\016\n\006if_del" +
      "\030( \001(\010\022\022\n\nif_publish\030) \001(\010\022.\n\007payload\030* " +
      "\003(\0132\035.look.meta.Brand.PayloadEntry\022\030\n\020la" +
      "st_modify_user\030+ \001(\003\022\023\n\013create_time\0302 \001(" +
      "\003\022\023\n\013update_time\0303 \001(\003\022\023\n\013delete_time\0304 ",
      "\001(\003\032.\n\014PayloadEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t:\0028\001B\035\n\020com.liukai.protoB\tMetaMod" +
      "elb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_look_meta_Brand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_look_meta_Brand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_look_meta_Brand_descriptor,
        new java.lang.String[] { "Id", "NameEn", "NameZh", "Pinyin", "SearchWord", "Country", "Description", "LogoPath", "LogoUrl", "CoverPath", "CoverUrl", "IfDel", "IfPublish", "Payload", "LastModifyUser", "CreateTime", "UpdateTime", "DeleteTime", });
    internal_static_look_meta_Brand_PayloadEntry_descriptor =
      internal_static_look_meta_Brand_descriptor.getNestedTypes().get(0);
    internal_static_look_meta_Brand_PayloadEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_look_meta_Brand_PayloadEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
